# Generated by Django 4.0.1 on 2022-01-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrycodes',
            old_name='country_code',
            new_name='countryCode',
        ),
        migrations.RenameField(
            model_name='countrycodes',
            old_name='country_name',
            new_name='countryName',
        ),
        migrations.RenameField(
            model_name='holidays',
            old_name='country_code',
            new_name='countryCode',
        ),
        migrations.RenameField(
            model_name='holidays',
            old_name='local_name',
            new_name='localName',
        ),
    ]
